//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tea.ModelSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInDelivery
    {
        public int IdProductInDelivery { get; set; }
        public double Quantity { get; set; }
        public int IdDelivery { get; set; }
        public int IdProduct { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Product Product { get; set; }
    }
}
